### ISSUE TITLE
Only show pdf of url

### ISSUE THREAD

**Issue by Mglt-b** [Android-for-Python/Webview-Example#3]
Hello

How can i show a .pdf with this webview on kivy android app?

actually it's only download the pdf, example : "https://www.nexans.fr/.rest/eservice/dam/v1/file/224502/ABS%201357%20Ind%20F.pdf"

But initial webview "import webview" on windows do the work

how can i do please ?

my code with this example lib:

```python
    def open_web(self, url):
        
        if platform == "win":
            self.open_webview_win(url)
            
        if platform == "android":
            try:
                self.open_webview_android(url)

            except NotImplementedError:
                print("GPS non disponible")
  
    def open_webview_win(self, url):
        import webview
        webview.create_window('Go-Fiber webview', url=url)
        webview.start()

    def open_webview_android(self, url):
        print("go",url)
        if platform == "android":
            from tools_go.android_webview.webview_x import WebView
            self.browser = WebView(url,
                                enable_javascript = True,
                                enable_downloads = False,
                                enable_zoom = True)
```

![image](https://github.com/Android-for-Python/Webview-Example/assets/20703341/7af1306d-9637-4daa-91a0-6b03bfee724e)

**Comment by RobertFlatt** [comment]
> How can i show a .pdf with this webview on kivy android app?

As far as I know the Android Webview  class does not render pdf. 
At the top of the page in the example it says HTML.
https://github.com/Android-for-Python/Webview-Example/blob/main/webview.py#L1

Comparing the functionality of an Android class and a Python package because they have the same name is probably not reliable.

You might want to look in the index
https://github.com/Android-for-Python/INDEX-of-Examples#viewer-examples

**Comment by Mglt-b** [comment]
Hi
Ty for Reply
Just try it
Works well
